# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d9269b638a222187ea2d72efd5f1d29aad8cad4bdf3afe9ee5915c5eb9b15c254dc1f186e69a671ce9a7224f1f121faa3c898c299b13238dbbcb42f2122e00f

test:
  secret_key_base: c629b1babbaa8a6ded41ca56c8612c741027c868ec2a15ecbdc3651b7a61a39372341c425d17a416fcf02d07cdb1f903bccb2fe9bff0ba2ccd3c7313e21f83ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
